/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LandlordRouteImport } from './routes/landlord'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaretakerRouteImport } from './routes/caretaker'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant.index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as LandlordIndexRouteImport } from './routes/landlord.index'
import { Route as CaretakerIndexRouteImport } from './routes/caretaker.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TenantSavedRouteImport } from './routes/tenant.saved'
import { Route as TenantProfileRouteImport } from './routes/tenant.profile'
import { Route as TenantMessagesRouteImport } from './routes/tenant.messages'
import { Route as TenantMapRouteImport } from './routes/tenant.map'
import { Route as ManagerDashboardRouteImport } from './routes/manager.dashboard'
import { Route as LandlordPropertiesRouteImport } from './routes/landlord.properties'
import { Route as LandlordLeadsRouteImport } from './routes/landlord.leads'
import { Route as LandlordDashboardRouteImport } from './routes/landlord.dashboard'
import { Route as LandlordAnalyticsRouteImport } from './routes/landlord.analytics'
import { Route as CaretakerDashboardRouteImport } from './routes/caretaker.dashboard'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as TenantReviewPropertyIdRouteImport } from './routes/tenant.review.$propertyId'
import { Route as TenantPropertyIdRouteImport } from './routes/tenant.property.$id'
import { Route as TenantMessagesIdRouteImport } from './routes/tenant.messages.$id'
import { Route as LandlordPropertiesNewRouteImport } from './routes/landlord.properties.new'
import { Route as LandlordDashboardPlanRouteImport } from './routes/landlord.dashboard.plan'

const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordRoute = LandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaretakerRoute = CaretakerRouteImport.update({
  id: '/caretaker',
  path: '/caretaker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const LandlordIndexRoute = LandlordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandlordRoute,
} as any)
const CaretakerIndexRoute = CaretakerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaretakerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TenantSavedRoute = TenantSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => TenantRoute,
} as any)
const TenantProfileRoute = TenantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TenantRoute,
} as any)
const TenantMessagesRoute = TenantMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TenantRoute,
} as any)
const TenantMapRoute = TenantMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => TenantRoute,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ManagerRoute,
} as any)
const LandlordPropertiesRoute = LandlordPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => LandlordRoute,
} as any)
const LandlordLeadsRoute = LandlordLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => LandlordRoute,
} as any)
const LandlordDashboardRoute = LandlordDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LandlordRoute,
} as any)
const LandlordAnalyticsRoute = LandlordAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LandlordRoute,
} as any)
const CaretakerDashboardRoute = CaretakerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CaretakerRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const TenantReviewPropertyIdRoute = TenantReviewPropertyIdRouteImport.update({
  id: '/review/$propertyId',
  path: '/review/$propertyId',
  getParentRoute: () => TenantRoute,
} as any)
const TenantPropertyIdRoute = TenantPropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => TenantRoute,
} as any)
const TenantMessagesIdRoute = TenantMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TenantMessagesRoute,
} as any)
const LandlordPropertiesNewRoute = LandlordPropertiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LandlordPropertiesRoute,
} as any)
const LandlordDashboardPlanRoute = LandlordDashboardPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => LandlordDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/caretaker': typeof CaretakerRouteWithChildren
  '/contact': typeof ContactRoute
  '/landlord': typeof LandlordRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/pricing': typeof PricingRoute
  '/tenant': typeof TenantRouteWithChildren
  '/auth/reset': typeof AuthResetRoute
  '/caretaker/dashboard': typeof CaretakerDashboardRoute
  '/landlord/analytics': typeof LandlordAnalyticsRoute
  '/landlord/dashboard': typeof LandlordDashboardRouteWithChildren
  '/landlord/leads': typeof LandlordLeadsRoute
  '/landlord/properties': typeof LandlordPropertiesRouteWithChildren
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/tenant/map': typeof TenantMapRoute
  '/tenant/messages': typeof TenantMessagesRouteWithChildren
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/saved': typeof TenantSavedRoute
  '/admin/': typeof AdminIndexRoute
  '/caretaker/': typeof CaretakerIndexRoute
  '/landlord/': typeof LandlordIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/landlord/dashboard/plan': typeof LandlordDashboardPlanRoute
  '/landlord/properties/new': typeof LandlordPropertiesNewRoute
  '/tenant/messages/$id': typeof TenantMessagesIdRoute
  '/tenant/property/$id': typeof TenantPropertyIdRoute
  '/tenant/review/$propertyId': typeof TenantReviewPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/auth/reset': typeof AuthResetRoute
  '/caretaker/dashboard': typeof CaretakerDashboardRoute
  '/landlord/analytics': typeof LandlordAnalyticsRoute
  '/landlord/dashboard': typeof LandlordDashboardRouteWithChildren
  '/landlord/leads': typeof LandlordLeadsRoute
  '/landlord/properties': typeof LandlordPropertiesRouteWithChildren
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/tenant/map': typeof TenantMapRoute
  '/tenant/messages': typeof TenantMessagesRouteWithChildren
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/saved': typeof TenantSavedRoute
  '/admin': typeof AdminIndexRoute
  '/caretaker': typeof CaretakerIndexRoute
  '/landlord': typeof LandlordIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/tenant': typeof TenantIndexRoute
  '/landlord/dashboard/plan': typeof LandlordDashboardPlanRoute
  '/landlord/properties/new': typeof LandlordPropertiesNewRoute
  '/tenant/messages/$id': typeof TenantMessagesIdRoute
  '/tenant/property/$id': typeof TenantPropertyIdRoute
  '/tenant/review/$propertyId': typeof TenantReviewPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/caretaker': typeof CaretakerRouteWithChildren
  '/contact': typeof ContactRoute
  '/landlord': typeof LandlordRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/pricing': typeof PricingRoute
  '/tenant': typeof TenantRouteWithChildren
  '/auth/reset': typeof AuthResetRoute
  '/caretaker/dashboard': typeof CaretakerDashboardRoute
  '/landlord/analytics': typeof LandlordAnalyticsRoute
  '/landlord/dashboard': typeof LandlordDashboardRouteWithChildren
  '/landlord/leads': typeof LandlordLeadsRoute
  '/landlord/properties': typeof LandlordPropertiesRouteWithChildren
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/tenant/map': typeof TenantMapRoute
  '/tenant/messages': typeof TenantMessagesRouteWithChildren
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/saved': typeof TenantSavedRoute
  '/admin/': typeof AdminIndexRoute
  '/caretaker/': typeof CaretakerIndexRoute
  '/landlord/': typeof LandlordIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/landlord/dashboard/plan': typeof LandlordDashboardPlanRoute
  '/landlord/properties/new': typeof LandlordPropertiesNewRoute
  '/tenant/messages/$id': typeof TenantMessagesIdRoute
  '/tenant/property/$id': typeof TenantPropertyIdRoute
  '/tenant/review/$propertyId': typeof TenantReviewPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/caretaker'
    | '/contact'
    | '/landlord'
    | '/manager'
    | '/pricing'
    | '/tenant'
    | '/auth/reset'
    | '/caretaker/dashboard'
    | '/landlord/analytics'
    | '/landlord/dashboard'
    | '/landlord/leads'
    | '/landlord/properties'
    | '/manager/dashboard'
    | '/tenant/map'
    | '/tenant/messages'
    | '/tenant/profile'
    | '/tenant/saved'
    | '/admin/'
    | '/caretaker/'
    | '/landlord/'
    | '/manager/'
    | '/tenant/'
    | '/landlord/dashboard/plan'
    | '/landlord/properties/new'
    | '/tenant/messages/$id'
    | '/tenant/property/$id'
    | '/tenant/review/$propertyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/auth/reset'
    | '/caretaker/dashboard'
    | '/landlord/analytics'
    | '/landlord/dashboard'
    | '/landlord/leads'
    | '/landlord/properties'
    | '/manager/dashboard'
    | '/tenant/map'
    | '/tenant/messages'
    | '/tenant/profile'
    | '/tenant/saved'
    | '/admin'
    | '/caretaker'
    | '/landlord'
    | '/manager'
    | '/tenant'
    | '/landlord/dashboard/plan'
    | '/landlord/properties/new'
    | '/tenant/messages/$id'
    | '/tenant/property/$id'
    | '/tenant/review/$propertyId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/caretaker'
    | '/contact'
    | '/landlord'
    | '/manager'
    | '/pricing'
    | '/tenant'
    | '/auth/reset'
    | '/caretaker/dashboard'
    | '/landlord/analytics'
    | '/landlord/dashboard'
    | '/landlord/leads'
    | '/landlord/properties'
    | '/manager/dashboard'
    | '/tenant/map'
    | '/tenant/messages'
    | '/tenant/profile'
    | '/tenant/saved'
    | '/admin/'
    | '/caretaker/'
    | '/landlord/'
    | '/manager/'
    | '/tenant/'
    | '/landlord/dashboard/plan'
    | '/landlord/properties/new'
    | '/tenant/messages/$id'
    | '/tenant/property/$id'
    | '/tenant/review/$propertyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CaretakerRoute: typeof CaretakerRouteWithChildren
  ContactRoute: typeof ContactRoute
  LandlordRoute: typeof LandlordRouteWithChildren
  ManagerRoute: typeof ManagerRouteWithChildren
  PricingRoute: typeof PricingRoute
  TenantRoute: typeof TenantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord': {
      id: '/landlord'
      path: '/landlord'
      fullPath: '/landlord'
      preLoaderRoute: typeof LandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caretaker': {
      id: '/caretaker'
      path: '/caretaker'
      fullPath: '/caretaker'
      preLoaderRoute: typeof CaretakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/landlord/': {
      id: '/landlord/'
      path: '/'
      fullPath: '/landlord/'
      preLoaderRoute: typeof LandlordIndexRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/caretaker/': {
      id: '/caretaker/'
      path: '/'
      fullPath: '/caretaker/'
      preLoaderRoute: typeof CaretakerIndexRouteImport
      parentRoute: typeof CaretakerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenant/saved': {
      id: '/tenant/saved'
      path: '/saved'
      fullPath: '/tenant/saved'
      preLoaderRoute: typeof TenantSavedRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/profile': {
      id: '/tenant/profile'
      path: '/profile'
      fullPath: '/tenant/profile'
      preLoaderRoute: typeof TenantProfileRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/messages': {
      id: '/tenant/messages'
      path: '/messages'
      fullPath: '/tenant/messages'
      preLoaderRoute: typeof TenantMessagesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/map': {
      id: '/tenant/map'
      path: '/map'
      fullPath: '/tenant/map'
      preLoaderRoute: typeof TenantMapRouteImport
      parentRoute: typeof TenantRoute
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/landlord/properties': {
      id: '/landlord/properties'
      path: '/properties'
      fullPath: '/landlord/properties'
      preLoaderRoute: typeof LandlordPropertiesRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/landlord/leads': {
      id: '/landlord/leads'
      path: '/leads'
      fullPath: '/landlord/leads'
      preLoaderRoute: typeof LandlordLeadsRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/landlord/dashboard': {
      id: '/landlord/dashboard'
      path: '/dashboard'
      fullPath: '/landlord/dashboard'
      preLoaderRoute: typeof LandlordDashboardRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/landlord/analytics': {
      id: '/landlord/analytics'
      path: '/analytics'
      fullPath: '/landlord/analytics'
      preLoaderRoute: typeof LandlordAnalyticsRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/caretaker/dashboard': {
      id: '/caretaker/dashboard'
      path: '/dashboard'
      fullPath: '/caretaker/dashboard'
      preLoaderRoute: typeof CaretakerDashboardRouteImport
      parentRoute: typeof CaretakerRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/tenant/review/$propertyId': {
      id: '/tenant/review/$propertyId'
      path: '/review/$propertyId'
      fullPath: '/tenant/review/$propertyId'
      preLoaderRoute: typeof TenantReviewPropertyIdRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/property/$id': {
      id: '/tenant/property/$id'
      path: '/property/$id'
      fullPath: '/tenant/property/$id'
      preLoaderRoute: typeof TenantPropertyIdRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/messages/$id': {
      id: '/tenant/messages/$id'
      path: '/$id'
      fullPath: '/tenant/messages/$id'
      preLoaderRoute: typeof TenantMessagesIdRouteImport
      parentRoute: typeof TenantMessagesRoute
    }
    '/landlord/properties/new': {
      id: '/landlord/properties/new'
      path: '/new'
      fullPath: '/landlord/properties/new'
      preLoaderRoute: typeof LandlordPropertiesNewRouteImport
      parentRoute: typeof LandlordPropertiesRoute
    }
    '/landlord/dashboard/plan': {
      id: '/landlord/dashboard/plan'
      path: '/plan'
      fullPath: '/landlord/dashboard/plan'
      preLoaderRoute: typeof LandlordDashboardPlanRouteImport
      parentRoute: typeof LandlordDashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CaretakerRouteChildren {
  CaretakerDashboardRoute: typeof CaretakerDashboardRoute
  CaretakerIndexRoute: typeof CaretakerIndexRoute
}

const CaretakerRouteChildren: CaretakerRouteChildren = {
  CaretakerDashboardRoute: CaretakerDashboardRoute,
  CaretakerIndexRoute: CaretakerIndexRoute,
}

const CaretakerRouteWithChildren = CaretakerRoute._addFileChildren(
  CaretakerRouteChildren,
)

interface LandlordDashboardRouteChildren {
  LandlordDashboardPlanRoute: typeof LandlordDashboardPlanRoute
}

const LandlordDashboardRouteChildren: LandlordDashboardRouteChildren = {
  LandlordDashboardPlanRoute: LandlordDashboardPlanRoute,
}

const LandlordDashboardRouteWithChildren =
  LandlordDashboardRoute._addFileChildren(LandlordDashboardRouteChildren)

interface LandlordPropertiesRouteChildren {
  LandlordPropertiesNewRoute: typeof LandlordPropertiesNewRoute
}

const LandlordPropertiesRouteChildren: LandlordPropertiesRouteChildren = {
  LandlordPropertiesNewRoute: LandlordPropertiesNewRoute,
}

const LandlordPropertiesRouteWithChildren =
  LandlordPropertiesRoute._addFileChildren(LandlordPropertiesRouteChildren)

interface LandlordRouteChildren {
  LandlordAnalyticsRoute: typeof LandlordAnalyticsRoute
  LandlordDashboardRoute: typeof LandlordDashboardRouteWithChildren
  LandlordLeadsRoute: typeof LandlordLeadsRoute
  LandlordPropertiesRoute: typeof LandlordPropertiesRouteWithChildren
  LandlordIndexRoute: typeof LandlordIndexRoute
}

const LandlordRouteChildren: LandlordRouteChildren = {
  LandlordAnalyticsRoute: LandlordAnalyticsRoute,
  LandlordDashboardRoute: LandlordDashboardRouteWithChildren,
  LandlordLeadsRoute: LandlordLeadsRoute,
  LandlordPropertiesRoute: LandlordPropertiesRouteWithChildren,
  LandlordIndexRoute: LandlordIndexRoute,
}

const LandlordRouteWithChildren = LandlordRoute._addFileChildren(
  LandlordRouteChildren,
)

interface ManagerRouteChildren {
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerDashboardRoute: ManagerDashboardRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface TenantMessagesRouteChildren {
  TenantMessagesIdRoute: typeof TenantMessagesIdRoute
}

const TenantMessagesRouteChildren: TenantMessagesRouteChildren = {
  TenantMessagesIdRoute: TenantMessagesIdRoute,
}

const TenantMessagesRouteWithChildren = TenantMessagesRoute._addFileChildren(
  TenantMessagesRouteChildren,
)

interface TenantRouteChildren {
  TenantMapRoute: typeof TenantMapRoute
  TenantMessagesRoute: typeof TenantMessagesRouteWithChildren
  TenantProfileRoute: typeof TenantProfileRoute
  TenantSavedRoute: typeof TenantSavedRoute
  TenantIndexRoute: typeof TenantIndexRoute
  TenantPropertyIdRoute: typeof TenantPropertyIdRoute
  TenantReviewPropertyIdRoute: typeof TenantReviewPropertyIdRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantMapRoute: TenantMapRoute,
  TenantMessagesRoute: TenantMessagesRouteWithChildren,
  TenantProfileRoute: TenantProfileRoute,
  TenantSavedRoute: TenantSavedRoute,
  TenantIndexRoute: TenantIndexRoute,
  TenantPropertyIdRoute: TenantPropertyIdRoute,
  TenantReviewPropertyIdRoute: TenantReviewPropertyIdRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CaretakerRoute: CaretakerRouteWithChildren,
  ContactRoute: ContactRoute,
  LandlordRoute: LandlordRouteWithChildren,
  ManagerRoute: ManagerRouteWithChildren,
  PricingRoute: PricingRoute,
  TenantRoute: TenantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
