/** Auto-generated by scripts/generate-kenya-locations.mjs — do not edit by hand. */

import locationsData from "./kenya-locations.json";

export type KenyaLocation = {
  readonly name: string;
  readonly county: string;
  readonly lat: number;
  readonly lng: number;
};

export const KENYA_LOCATIONS: readonly KenyaLocation[] = locationsData as readonly KenyaLocation[];

export const KENYA_COUNTIES: readonly string[] = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
] as const;

/** Nairobi estates keep short names for backward compatibility with existing listings. */
export function neighborhoodStorageValue(location: Pick<KenyaLocation, "name" | "county">): string {
  if (location.county === "Nairobi") return location.name;
  return `${location.name}, ${location.county}`;
}

export function locationLabel(location: Pick<KenyaLocation, "name" | "county">): string {
  return neighborhoodStorageValue(location);
}

export function matchLocation(input: string): KenyaLocation | null {
  const norm = input.trim().toLowerCase();
  if (!norm) return null;

  const exact = KENYA_LOCATIONS.find(
    (loc) =>
      loc.name.toLowerCase() === norm ||
      neighborhoodStorageValue(loc).toLowerCase() === norm ||
      `${loc.name}, ${loc.county}`.toLowerCase() === norm,
  );
  if (exact) return exact;

  return (
    KENYA_LOCATIONS.find((loc) => {
      const label = neighborhoodStorageValue(loc).toLowerCase();
      return (
        norm.includes(loc.name.toLowerCase()) ||
        loc.name.toLowerCase().includes(norm) ||
        norm.includes(label) ||
        label.includes(norm)
      );
    }) ?? null
  );
}

export function areasForCounty(county: string): readonly KenyaLocation[] {
  return KENYA_LOCATIONS.filter((loc) => loc.county === county);
}

export const KENYA_LOCATION_LABELS: readonly string[] = KENYA_LOCATIONS.map((loc) =>
  locationLabel(loc),
) as readonly string[];

/** Short names used in filters and legacy Nairobi listings. */
export const NAIROBI_NEIGHBORHOODS: readonly string[] = KENYA_LOCATIONS.filter(
  (loc) => loc.county === "Nairobi",
).map((loc) => loc.name) as readonly string[];

export const ALLOWED_NEIGHBORHOOD_FILTERS: ReadonlySet<string> = new Set([
  ...KENYA_LOCATIONS.flatMap((loc) => [loc.name, neighborhoodStorageValue(loc)]),
  ...KENYA_COUNTIES.map((county) => `All ${county}`),
]);

export function countyWideFilterValue(county: string): string {
  return `All ${county}`;
}

export function parseCountyWideFilter(value: string): string | null {
  if (!value.startsWith("All ")) return null;
  const county = value.slice(4).trim();
  return KENYA_COUNTIES.includes(county) ? county : null;
}
